/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.ConvertirTxt;
import Datos.DatosEmisor;
import Datos.ModeloExcel;
import java.io.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author USER
 */
public class Generador extends javax.swing.JFrame {
    File archivo;
    File carpetaSalida;
    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
        this.setLocationRelativeTo(null);
        tblDatos.setCellSelectionEnabled(false);
        tblDatos.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        txtCarpeta = new javax.swing.JTextField();
        btnArchivo = new javax.swing.JButton();
        btnCarpeta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRucDni = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtNomComercial = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese ruta de inicio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ruta de salida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));
        jPanel1.add(txtArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));
        jPanel1.add(txtCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, -1));

        btnArchivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnArchivo.setText("...");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 50, -1));

        btnCarpeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCarpeta.setText("...");
        btnCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 50, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos Emisor");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 24, 390, -1));

        jLabel5.setText("RUC:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel6.setText("Razón Social:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        jLabel7.setText("Nombre Comercial:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));
        jPanel2.add(txtRucDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 240, -1));

        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        jPanel2.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 240, -1));
        jPanel2.add(txtNomComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 410, 220));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 120, 30));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 600, 400));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos del excel ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 600, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        JFileChooser ch = new JFileChooser();
        
        FileNameExtensionFilter filtroExcel = new FileNameExtensionFilter(
            "Archivos de Excel (*.xlsx, *.xls)", "xlsx", "xls");
        
        ch.setFileFilter(filtroExcel);
        ch.setAcceptAllFileFilterUsed(false); 
        
        int retornarValor = ch.showOpenDialog(null);
        
        if (retornarValor == JFileChooser.APPROVE_OPTION) {
            archivo = ch.getSelectedFile();
            String nombreArchivo = archivo.getAbsolutePath();
            txtArchivo.setText(nombreArchivo);
            ModeloExcel leer = new ModeloExcel();
            leer.leerExcel(nombreArchivo, tblDatos);
        }else{
            JOptionPane.showMessageDialog(this, "No seleciono un archivo");
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaActionPerformed
        JFileChooser ruta = new JFileChooser();
        ruta.setFileSelectionMode(ruta.DIRECTORIES_ONLY);
        int retornarValor = ruta.showOpenDialog(null);
        
        if (retornarValor == JFileChooser.APPROVE_OPTION) {
            carpetaSalida = ruta.getSelectedFile();
            String nombreCarpeta =  carpetaSalida.getAbsolutePath();
            txtCarpeta.setText(nombreCarpeta);
        }else{
            JOptionPane.showMessageDialog(this, "No selecciono una carpeta");
        }
    }//GEN-LAST:event_btnCarpetaActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String rucDni = txtRucDni.getText();
        String razonSocial = txtRazonSocial.getText();
        String nameComercial = txtNomComercial.getText();
        
        //Validacion del DNI y RUC
        if (rucDni.length()!=8 && rucDni.length()!=11) {//Detener el proceso del metodo actual
            JOptionPane.showMessageDialog(this, "EL RUC/DNI debe contener exactamente 8 o 11 caracteres");
            return;//Evita la ejecución o continuación del resto del metodo
        }
        
        DatosEmisor dato = new DatosEmisor(rucDni, razonSocial, nameComercial);
        
        if (carpetaSalida !=null && tblDatos !=null) {//Validar que se selecciono una carpeta y existe la tabla
            ConvertirTxt genera = new ConvertirTxt();
            genera.generarTXTTabla(tblDatos, carpetaSalida, dato);
            JOptionPane.showMessageDialog(this, "Archivos generados exitosamente en la carpeta");
        }else{
            JOptionPane.showMessageDialog(this, "Error: Selecionje una carpeta");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generador().setVisible(true);
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCarpeta;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtCarpeta;
    private javax.swing.JTextField txtNomComercial;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRucDni;
    // End of variables declaration//GEN-END:variables
}
