/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import datos.ConvertirTxt;
import datos.InfoEmisor;
import datos.LectorExcel;
import java.io.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class GeneradorTXT extends javax.swing.JFrame {

    // Archivo Excel seleccionado
    File archivo;

    // Carpeta donde se guardarán los archivos generados
    File carpetaSalida;

    /**
     * Creates new form Generador
     */
    /**
     * Constructor: inicializa la interfaz y configura la tabla
     */
    public GeneradorTXT() {
        initComponents(); // Carga los componentes visuales
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla

        // Configuración de la tabla: solo lectura, sin selección de celdas individuales
        tblDatos.setCellSelectionEnabled(false);
        tblDatos.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        txtCarpeta = new javax.swing.JTextField();
        btnArchivo = new javax.swing.JButton();
        btnCarpeta = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRucDni = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtNomComercial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generador de txt");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 450, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ruta de inicio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ruta de salida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));
        jPanel1.add(txtArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 200, -1));
        jPanel1.add(txtCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, -1));

        btnArchivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnArchivo.setText("...");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 50, -1));

        btnCarpeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCarpeta.setText("...");
        btnCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, -1));

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 150, 50));

        jLabel5.setText("RUC:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, 30));

        jLabel6.setText("Razón Social:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        jLabel7.setText("Nombre Comercial:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 30));

        txtRucDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucDniActionPerformed(evt);
            }
        });
        jPanel1.add(txtRucDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 240, -1));

        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        jPanel1.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 240, -1));
        jPanel1.add(txtNomComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 240, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 390, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1110, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // Obtener datos del emisor desde los campos de texto
        String rucDni = txtRucDni.getText();
        String razonSocial = txtRazonSocial.getText();
        String nameComercial = txtNomComercial.getText();

        // Validar longitud del RUC/DNI (debe ser 8 o 11 caracteres)
        if (rucDni.length() != 8 && rucDni.length() != 11) {
            JOptionPane.showMessageDialog(this, "EL RUC/DNI debe contener exactamente 8 o 11 caracteres");
            return; // Detener ejecución si no cumple
        }

        // Crear objeto con los datos del emisor
        InfoEmisor dato = new InfoEmisor(rucDni, razonSocial, nameComercial);

        // Verificar que se haya seleccionado una carpeta y que la tabla tenga datos
        if (carpetaSalida != null && tblDatos != null) {
            ConvertirTxt genera = new ConvertirTxt();
            genera.generarTXTTabla(tblDatos, carpetaSalida, dato); // Generar archivos TXT
            JOptionPane.showMessageDialog(this, "Archivos generados exitosamente en la carpeta");
        } else {
            JOptionPane.showMessageDialog(this, "Error: Seleccione una carpeta");
        }

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaActionPerformed
        // Abrir selector de carpetas
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Solo permite elegir carpetas

        int resultado = selector.showOpenDialog(null); // Mostrar diálogo

        if (resultado == JFileChooser.APPROVE_OPTION) {
            // Carpeta seleccionada
            carpetaSalida = selector.getSelectedFile();
            txtCarpeta.setText(carpetaSalida.getAbsolutePath()); // Mostrar ruta en el campo de texto
        } else {
            JOptionPane.showMessageDialog(this, "No se seleccionó ninguna carpeta");
        }
    }//GEN-LAST:event_btnCarpetaActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // Abrir selector de archivos Excel
        JFileChooser selector = new JFileChooser();

        // Aplicar filtro para mostrar solo archivos Excel válidos
        FileNameExtensionFilter filtroExcel = new FileNameExtensionFilter(
                "Archivos de Excel (*.xlsx, *.xls, *.xlsm)", "xlsx", "xls", "xlsm");
        selector.setFileFilter(filtroExcel);
        selector.setAcceptAllFileFilterUsed(false); // Desactiva opción "Todos los archivos"

        int resultado = selector.showOpenDialog(null); // Mostrar diálogo

        if (resultado == JFileChooser.APPROVE_OPTION) {
            // Archivo seleccionado
            archivo = selector.getSelectedFile();
            String rutaArchivo = archivo.getAbsolutePath();
            txtArchivo.setText(rutaArchivo); // Mostrar ruta en el campo de texto

            // Leer contenido del archivo y cargarlo en la tabla
            LectorExcel lector = new LectorExcel();
            lector.cargarExcel(rutaArchivo, tblDatos);
        } else {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo");
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void txtRucDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucDniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneradorTXT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneradorTXT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneradorTXT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneradorTXT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneradorTXT().setVisible(true);
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(GeneradorTXT.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCarpeta;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtCarpeta;
    private javax.swing.JTextField txtNomComercial;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRucDni;
    // End of variables declaration//GEN-END:variables
}
